apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: rohitemerico/productservice:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"

            - name: ConnectionStrings__DefaultConnection
              value: "Host=product-db;Port=5432;Database=productsdb;Username=postgres;Password=postgres;"